# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update Readme

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Update .md File
      run: |
        python update.py
    - name: Push the change
      run: |
          git config --global user.name 'Junhyeong-B'
          git config --global user.email 'aowlr0513@gmail.com'
          git commit -am "Automated update of README.md" || true
          git push
